pr:
  autoCancel: false
  branches:
    include:
    - '*'
  drafts: false
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  
schedules:
- cron: '0 0 * * Tue,Fr'
  displayName: 'Bi-weekly build (UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - main
trigger: none

variables:
- group: deprecated-tasks # can override AZDO_ORG_SERVICE_URL, AZDO_PROJECT, AZDO_PERSONAL_ACCESS_TOKEN
- name: scriptDirectory
  value: $(Build.SourcesDirectory)/scripts/pipelines

jobs:
- job: retrievalScripts
  displayName: 'Deprecated tasks'

  pool:
    name: 'Azure Pipelines'
    vmImage: ubuntu-latest

  steps:
  - pwsh: |
      Get-ChildItem -Path Env: -Recurse -Include * | Sort-Object -Property Name
      ./find_deprecated_task_usage.ps1
    displayName: 'Find deprecated tasks in $(System.TeamProject)'
    workingDirectory: $(scriptDirectory)
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - publish: $(Build.ArtifactStagingDirectory)
    displayName: 'Publish CSV files'
    artifact: DeprecatedTasks-$(System.PlanId)-$(System.JobId)