name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-$(Build.BuildId)

parameters:
- name: serviceConnection
  displayName: Override Service Connection
  type: string
  default: '<from azdoConnection variable>'

pr:
  autoCancel: false
  branches:
    include:
    - '*'
  drafts: false
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  
schedules:
- cron: '0 0 * * Tue,Fr'
  displayName: 'Bi-weekly build (UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - master
trigger: none

variables:
- name: scriptDirectory
  value: $(Build.SourcesDirectory)/scripts
- name: organizationName
  value: ${{ split(variables['System.CollectionUri'],'/')[3] }}
- name: AZURE_CORE_ONLY_SHOW_ERRORS
  value: true
- name: AZURE_EXTENSION_USE_DYNAMIC_INSTALL
  value: yes_without_prompt
- name: serviceConnection
  ${{ if eq(parameters.serviceConnection, '<from azdoConnection variable>') }}:
    value: $[ variables['azdoConnection'] ]
  ${{ else }}:
    value: '${{ parameters.serviceConnection }}'

jobs:
- job: retrievalScripts
  displayName: 'Non-modifying tests'

  pool:
    name: 'Azure Pipelines'
    vmImage: ubuntu-latest

  steps:
  - task: AzureCLI@2
    displayName: 'rename_service_connection_applications.ps1'
    inputs:
      azureSubscription: '$(azureConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        ./get_organization_id.ps1
      failOnStandardError: true
      workingDirectory: '$(scriptDirectory)'
