parameters:
- name: includeUsage
  displayName: Process pipeline runs to find deprecated tasks
  type: boolean
  default: true
- name: variableGroup
  displayName: Variable group with AZDO_* variables
  type: string
  default: '<variable group name>'
  
name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-${{ replace(parameters.variableGroup,'<variable group name>','') }}-$(Build.BuildId)

pr:
  autoCancel: false
  branches:
    include:
    - '*'
  drafts: false
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  
schedules:
- cron: '0 0 * * Tue,Fr'
  displayName: 'Bi-weekly build (UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - main
trigger: none

variables:
- ${{ if ne(parameters.variableGroup,'<variable group name>') }}:
  - group: ${{ parameters.variableGroup }} # can override AZDO_ORG_SERVICE_URL, AZDO_PROJECT, AZDO_PERSONAL_ACCESS_TOKEN
- name: scriptDirectory
  value: $(Build.SourcesDirectory)/scripts/pipelines

jobs:
- job: retrievalScripts
  displayName: 'Deprecated tasks'

  pool:
    name: 'Azure Pipelines'
    vmImage: ubuntu-latest

  steps:
  - pwsh: |
      ./list_deprecated_tasks.ps1 -ListTasksOnly:(!$${{ parameters.includeUsage }})
    displayName: 'Find deprecated tasks'
    workingDirectory: $(scriptDirectory)
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - publish: $(Build.ArtifactStagingDirectory)
    displayName: 'Publish CSV file(s)'
    artifact: DeprecatedTasks-$(System.PlanId)-$(System.JobId)